"""refactor columns and keep old embeddings

Revision ID: 3ad99044099c
Revises: e76d37390542
Create Date: 2025-10-07 11:45:43.208962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ad99044099c'
down_revision: Union[str, Sequence[str], None] = 'e76d37390542'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('face_count', sa.Integer(), nullable=True))
    op.drop_column('user', 'drive_access_token')
    op.drop_column('user', 'drive_token_expiry')
    op.drop_column('user', 'is_drive_connected')
    op.drop_column('user', 'drive_refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('drive_refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_drive_connected', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('drive_token_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('drive_access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('media', 'face_count')
    # ### end Alembic commands ###
