"""add google drive cols

Revision ID: c0a8af89f297
Revises: 69c5b50d9710
Create Date: 2025-09-17 15:19:35.028998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'c0a8af89f297'
down_revision: Union[str, Sequence[str], None] = '69c5b50d9710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('google_access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('google_refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('google_token_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'google_token_expiry')
    op.drop_column('user', 'google_refresh_token')
    op.drop_column('user', 'google_access_token')
    op.drop_column('media', 'external_id')
    # ### end Alembic commands ###
