"""add timestamps

Revision ID: 54325de60a80
Revises: beb1d808aef2
Create Date: 2025-10-11 22:35:38.716343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54325de60a80'
down_revision: Union[str, Sequence[str], None] = 'beb1d808aef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facecluster', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('facecluster', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('faceembedding', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('faceembedding', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('faceembedding', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('faceembedding', 'updated_at')
    op.drop_column('facecluster', 'updated_at')
    op.drop_column('facecluster', 'created_at')
    # ### end Alembic commands ###
