"""add downloads table

Revision ID: 91ed5e8ccdd8
Revises: 71239691c915
Create Date: 2025-10-13 21:29:48.019191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '91ed5e8ccdd8'
down_revision: Union[str, Sequence[str], None] = '71239691c915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_jobs',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_files', sa.Integer(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cluster_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['facecluster.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_download_jobs_expires_at'), 'download_jobs', ['expires_at'], unique=False)
    op.create_index(op.f('ix_download_jobs_id'), 'download_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_download_jobs_status'), 'download_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_download_jobs_user_id'), 'download_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_download_jobs_user_id'), table_name='download_jobs')
    op.drop_index(op.f('ix_download_jobs_status'), table_name='download_jobs')
    op.drop_index(op.f('ix_download_jobs_id'), table_name='download_jobs')
    op.drop_index(op.f('ix_download_jobs_expires_at'), table_name='download_jobs')
    op.drop_table('download_jobs')
    # ### end Alembic commands ###
