"""add media_ids col

Revision ID: 65a1f0932a3c
Revises: 91ed5e8ccdd8
Create Date: 2025-10-13 21:37:47.846173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '65a1f0932a3c'
down_revision: Union[str, Sequence[str], None] = '91ed5e8ccdd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download_jobs', sa.Column('media_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('download_jobs', 'media_ids')
    # ### end Alembic commands ###
