"""addmedia uploaded_by col

Revision ID: 5d2539477966
Revises: a8d57529e748
Create Date: 2025-08-30 08:23:56.347318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5d2539477966'
down_revision: Union[str, Sequence[str], None] = 'a8d57529e748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('uploaded_by', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_media_uploaded_by'), 'media', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_uploaded_by'), table_name='media')
    op.drop_column('media', 'uploaded_by')
    # ### end Alembic commands ###
