"""add media approval status col

Revision ID: ea4d93be873d
Revises: 3ad99044099c
Create Date: 2025-10-08 22:42:59.770901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'ea4d93be873d'
down_revision: Union[str, Sequence[str], None] = '3ad99044099c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mediaembedding', 'status',
               existing_type=sa.VARCHAR(),
               server_default='pending',
               nullable=False)
    op.add_column('mediausage', sa.Column('approval_status', sa.String(), nullable=True))
    op.add_column('mediausage', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.create_index('idx_media_usage_approval', 'mediausage', ['owner_type', 'approval_status'], unique=False)
    op.create_index(op.f('ix_mediausage_approval_status'), 'mediausage', ['approval_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mediausage_approval_status'), table_name='mediausage')
    op.drop_index('idx_media_usage_approval', table_name='mediausage')
    op.drop_column('mediausage', 'approved_at')
    op.drop_column('mediausage', 'approval_status')
    op.alter_column('mediaembedding', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               nullable=True)
    # ### end Alembic commands ###
