"""add timestamps to eventparticipant table

Revision ID: 917b0d7bf1bb
Revises: 889090259858
Create Date: 2025-09-04 21:33:04.423770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '917b0d7bf1bb'
down_revision: Union[str, Sequence[str], None] = '889090259858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventparticipant', sa.Column('id', sa.Integer(), nullable=True))
    op.add_column('eventparticipant', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('eventparticipant', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('eventparticipant', 'updated_at')
    op.drop_column('eventparticipant', 'created_at')
    op.drop_column('eventparticipant', 'id')
    # ### end Alembic commands ###
