"""increase embedding dimensions

Revision ID: f468053a19f3
Revises: a4ec6abe3909
Create Date: 2025-09-11 23:48:49.793578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'f468053a19f3'
down_revision: Union[str, Sequence[str], None] = 'a4ec6abe3909'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('faceembedding', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=2622),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=4096),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('faceembedding', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=4096),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=2622),
               existing_nullable=True)
    # ### end Alembic commands ###
