"""add status check cols

Revision ID: eb9ba166d49d
Revises: 7161d8c6ee9e
Create Date: 2025-10-11 11:57:39.071132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'eb9ba166d49d'
down_revision: Union[str, Sequence[str], None] = '7161d8c6ee9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faceembedding', sa.Column('status', sa.String(), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faceembedding', 'status')
    # ### end Alembic commands ###
