"""add privacy settings cols

Revision ID: 483d076af940
Revises: 917b0d7bf1bb
Create Date: 2025-09-06 19:53:29.618936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '483d076af940'
down_revision: Union[str, Sequence[str], None] = '917b0d7bf1bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('allow_contributions', sa.Boolean(), nullable=True))
    op.add_column('event', sa.Column('auto_approve_uploads', sa.Boolean(), nullable=True))
    op.alter_column('event', 'privacy',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'privacy',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('event', 'auto_approve_uploads')
    op.drop_column('event', 'allow_contributions')
    # ### end Alembic commands ###
