"""remove_cover_photo_column_from_event

Revision ID: 8957553e3bcb
Revises: 91b8e13b6efd
Create Date: 2025-09-19 12:16:24.376280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '8957553e3bcb'
down_revision: Union[str, Sequence[str], None] = '91b8e13b6efd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'cover_photo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('cover_photo', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
