"""refactor media url cols

Revision ID: 91b8e13b6efd
Revises: c04040c6b5e6
Create Date: 2025-09-18 20:01:56.987366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '91b8e13b6efd'
down_revision: Union[str, Sequence[str], None] = 'c04040c6b5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('external_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('media', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('media', 'external_url')
    # ### end Alembic commands ###
