"""add status tracking to media embeddings

Revision ID: a3801658f534
Revises: 056fb7444f40
Create Date: 2025-09-24 19:17:20.781232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'a3801658f534'
down_revision: Union[str, Sequence[str], None] = '056fb7444f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mediaembedding', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('mediaembedding', sa.Column('processed_at', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('mediaembedding', sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mediaembedding', 'error_message')
    op.drop_column('mediaembedding', 'processed_at')
    op.drop_column('mediaembedding', 'status')
    # ### end Alembic commands ###
