"""auto approve participants

Revision ID: 2089d98b5e91
Revises: 65a1f0932a3c
Create Date: 2025-10-13 23:34:01.576321

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '2089d98b5e91'
down_revision: Union[str, Sequence[str], None] = '65a1f0932a3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('auto_approve_participants', sa.Boolean(), server_default='False', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'auto_approve_participants')
    # ### end Alembic commands ###
