"""add is_drive_connected col default

Revision ID: 264d1d186524
Revises: 6e6130abdc64
Create Date: 2025-09-17 21:46:32.545031

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '264d1d186524'
down_revision: Union[str, Sequence[str], None] = '6e6130abdc64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_drive_connected',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_drive_connected',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
