"""add uploader col tomedia

Revision ID: ff8399d49d38
Revises: 5d2539477966
Create Date: 2025-08-30 08:47:55.509415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ff8399d49d38'
down_revision: Union[str, Sequence[str], None] = '5d2539477966'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media', 'uploaded_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_media_uploaded_by'), table_name='media')
    op.create_foreign_key(None, 'media', 'user', ['uploaded_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.create_index(op.f('ix_media_uploaded_by'), 'media', ['uploaded_by'], unique=False)
    op.alter_column('media', 'uploaded_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
