"""add tags to media

Revision ID: d787357ce3fb
Revises: 54325de60a80
Create Date: 2025-10-13 11:53:34.988543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'd787357ce3fb'
down_revision: Union[str, Sequence[str], None] = '54325de60a80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('mediausage', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mediausage', 'tags')
    op.drop_column('media', 'tags')
    # ### end Alembic commands ###
