"""add embeddings retry count

Revision ID: 4ff081210921
Revises: cb45e1429f32
Create Date: 2025-10-05 10:53:22.650235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '4ff081210921'
down_revision: Union[str, Sequence[str], None] = 'cb45e1429f32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mediaembedding', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mediaembedding', 'retry_count')
    # ### end Alembic commands ###
