"""add tags col to faceembedding

Revision ID: f090dee435c6
Revises: d787357ce3fb
Create Date: 2025-10-13 12:24:42.653081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'f090dee435c6'
down_revision: Union[str, Sequence[str], None] = 'd787357ce3fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faceembedding', sa.Column('tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faceembedding', 'tags')
    # ### end Alembic commands ###
