"""make embeddings unique per media

Revision ID: e76d37390542
Revises: 9c35b100f562
Create Date: 2025-10-06 22:58:20.498607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'e76d37390542'
down_revision: Union[str, Sequence[str], None] = '9c35b100f562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'mediaembedding', ['media_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mediaembedding', type_='unique')
    # ### end Alembic commands ###
