"""take a list of embeddings per image

Revision ID: 056fb7444f40
Revises: 8957553e3bcb
Create Date: 2025-09-21 13:36:03.609049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '056fb7444f40'
down_revision: Union[str, Sequence[str], None] = '8957553e3bcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mediaembedding', sa.Column('embeddings', sa.JSON(), nullable=True))
    op.drop_column('mediaembedding', 'embedding')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mediaembedding', sa.Column('embedding', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('mediaembedding', 'embeddings')
    # ### end Alembic commands ###
