"""scope face clusters to events

Revision ID: 71239691c915
Revises: f090dee435c6
Create Date: 2025-10-13 16:54:06.008278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '71239691c915'
down_revision: Union[str, Sequence[str], None] = 'f090dee435c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facecluster', sa.Column('event_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_facecluster_event_id', 'facecluster', 'event', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_facecluster_event_id', 'facecluster', type_='foreignkey')
    op.drop_column('facecluster', 'event_id')
    # ### end Alembic commands ###
