"""add stats and refactor

Revision ID: e88e08c859f3
Revises: 009b839eb27b
Create Date: 2025-08-28 23:00:44.174144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e88e08c859f3'
down_revision: Union[str, Sequence[str], None] = '009b839eb27b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('num_joined', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('num_hosted', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('num_uploads', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('num_photos', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_column('user', 'disabled')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.VARCHAR(), server_default=sa.text("'user'"), nullable=False))
    op.add_column('user', sa.Column('disabled', sa.BOOLEAN(), nullable=False))
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.drop_column('user', 'num_photos')
    op.drop_column('user', 'num_uploads')
    op.drop_column('user', 'num_hosted')
    op.drop_column('user', 'num_joined')
    # ### end Alembic commands ###
