"""rename google drive cols

Revision ID: 738e211f0212
Revises: c0a8af89f297
Create Date: 2025-09-17 21:32:35.503780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '738e211f0212'
down_revision: Union[str, Sequence[str], None] = 'c0a8af89f297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('drive_access_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('drive_refresh_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('drive_token_expiry', sa.DateTime(), nullable=True))
    op.drop_column('user', 'google_access_token')
    op.drop_column('user', 'google_refresh_token')
    op.drop_column('user', 'google_token_expiry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('google_token_expiry', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('google_refresh_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('google_access_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user', 'drive_token_expiry')
    op.drop_column('user', 'drive_refresh_token')
    op.drop_column('user', 'drive_access_token')
    # ### end Alembic commands ###
