"""add drive connection tracking col

Revision ID: 6e6130abdc64
Revises: 738e211f0212
Create Date: 2025-09-17 21:41:34.369793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '6e6130abdc64'
down_revision: Union[str, Sequence[str], None] = '738e211f0212'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_drive_connected', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_drive_connected')
    # ### end Alembic commands ###
