"""update embeddings size

Revision ID: 80f13bbee582
Revises: 264d1d186524
Create Date: 2025-09-18 18:11:20.491132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '80f13bbee582'
down_revision: Union[str, Sequence[str], None] = '264d1d186524'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('faceembedding', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=4096),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('faceembedding', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=512),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=4096),
               existing_nullable=True)
    # ### end Alembic commands ###
